### ISSUE TITLE
Lights turn green when all tests fail

### ISSUE THREAD

**Issue by kkterai** [learn-co-curriculum/space-invaders#18]
I opened the lab and ran learn. "Passed Local Tests" lights turned green even though the tests failed locally.

<img width="157" alt="screen shot 2017-05-27 at 11 46 55 am" src="https://cloud.githubusercontent.com/assets/19792273/26523749/717c18e2-42d2-11e7-9b76-d499fa25192f.png">
![screen shot 2017-05-27 at 11 47 04 am](https://cloud.githubusercontent.com/assets/19792273/26523756/9bab75b8-42d2-11e7-93c5-6d90977958ab.png)
![screen shot 2017-05-27 at 11 47 15 am](https://cloud.githubusercontent.com/assets/19792273/26523759/c00ff6f4-42d2-11e7-9aae-548ee286bc90.png)
![screen shot 2017-05-27 at 11 47 25 am](https://cloud.githubusercontent.com/assets/19792273/26523760/c0109b54-42d2-11e7-9142-33c6d27d0925.png)

**Comment by DanielSeehausen** [comment]
should be updated! thank you for bringing this to our attention! if you are still able to replicate this problem @kkterai please ping me directly
