### ISSUE TITLE
order of tests incorrect

### ISSUE THREAD

**Issue by jaredianmills** [learn-co-curriculum/space-invaders#23]
https://github.com/learn-co-curriculum/space-invaders/blob/e64c1322cfddae98e965ea2a82e617fe5b170b72/test/crewMemberSpaceshipTest.js#L46

A ship defaults to having its warp drive "disengaged". This test has a crew member engaging warp drive and then expects warp drive to be "disengaged". This should change to "engaged" and then the subsequent test, when warp drive is engaged again, should turn the warp drive back to "disengaged"

**Comment by realAndrewCohn** [comment]
https://github.com/learn-co-curriculum/space-invaders/blob/e64c1322cfddae98e965ea2a82e617fe5b170b72/test/crewMemberSpaceshipTest.js#L45

Only the pilot should be able to engage warp drive. Closing issue
