### ISSUE TITLE
Passing scope to forEach not yet explained

### ISSUE THREAD

**Issue by kthffmn** [learn-co-curriculum/space-invaders#4]
The forEach function changes the value of `this`. To avoid this issue (**this** issue!), the solution saves a variable `that` as `this` prior to the loop. Though this is solution does work, it's not ideal, plus the idea of `forEach` changing the scope hasn't been explained. 

There should either be frontmatter in this lab or in a separate readme that describes what to do when you encounter a scoping issues when working with objects in JS. See [this StackOverflow post](http://stackoverflow.com/a/19733805/2890716)  for more details.
 
The solution in `lib/spaceship.js` features this code:

```javascript
// line 20
function(){
  var that = this;
  this.crew.forEach(function(crewMember){
    crewMember.currentShip = that;
  });
}
```

**Comment by AnnJohn** [comment]
Iceboxing for now
